### PR TITLE
mat64: remove interfaces

### LINKED ISSUE #138: mat64: consider retiring less used interface definitions
The interface definitions in matrix.go served a useful purpose in defining the direction of development for mat64. We now have a fairly well defined set of interfaces based on the concrete types, so with the exception of interfaces that are used within the package or are likely to be useful to clients we should start considering retirement for these.

Please add you thoughts on which should be retired and which should stay.

### PR DESCRIPTION
**Pull request by kortschak**
Fixes #138.

@btracey Please take a look.

### CODE REVIEW

File: mat64/dense.go [hunk 1]
```diff
@@ -462,9 +449,9 @@ func (m *Dense) Stack(a, b Matrix) {
 }
 
 // Augment creates the augmented matrix of a and b, where b is placed in the
-// greater indexed columns.
-//
-// See the Augmenter interface for more information.
+// greater indexed columns. Augment will panic if the two input matrices do
+// not have the same number of rows or the augmented matrix is not the same
```
Comment (btracey) [inline mat64/dense.go]: "or the constructed augmented matrix", this way there is no confusion with a being the augmented matrix.

**Comment by btracey** [comment]
LGTM minus minor comment.

Another big issue down!
